Bootstrap: docker

From: continuumio/anaconda3

Stage: Paint-shop

%labels

PLACEHOLDER


%post

su -  root # USER root

apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get install -y git bzip cmake libboost-all-dev parallel zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

conda --version

conda install -n base -c conda-forge mamba

mkdir -p /snakey

cd /snakey

PROJECT_DIR=/snakey

git clone https://github.com/beliveau-lab/PaintSHOP_pipeline.git \
    && cd PaintSHOP_pipeline/ \
    && mamba env create -f environment.yml
