name: PaintSHOP_pipeline
channels:
 - bioconda
 - conda-forge
dependencies:
 - snakemake-minimal=5.2.4
 - python=3.6
 - biopython=1.73
 - bowtie2=2.3.5
 - jellyfish=2.2
 - numpy=1.16.2
 - pandas=0.24.2
 - pybedtools=0.8.0
 - scikit-learn=0.20.3
 - xgboost=0.82
 - samtools=1.9 
